pipeline {
    agent {node {label "AGENT-1"}}

    stages {
        stage('init') {
            steps {
                sh '''
                    cd 01vpc
                    terraform init
                '''
            }
        }
        stage('plan') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}