pipeline {
    agent {node {label "AGENT-1"}}
    options {
        ansiColor('xterm')  // Enables ANSI colors in Jenkins output
    }

    stages {
        stage('init') {
            steps {
                sh '''
                    pwd
                    cd 01vpc
                    terraform init
                '''
            }
        }
        stage('plan') {
            steps {
                sh '''
                pwd
                cd 01vpc
                pwd
                ls -ltr
                terraform plan
                ''' 
            }
        }
        stage('approval') {
            steps{
                input 'Shall I apply?'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}