pipeline {
    agent {node {label "AGENT-1"}}

    stages {
        stage('init') {
            steps {
                sh '''
                    pwd
                    cd 01vpc
                    terraform init
                '''
            }
        }
        stage('plan') {
            steps {
                sh 'pwd'
                sh 'cd 01vpc'
                sh 'pwd'
                sh 'ls -ltr'
                echo 'planning'
                sh 'terraform plan' 
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}